"""initial migration

Revision ID: 142d4fc706bb
Revises: 
Create Date: 2026-05-10 21:35:17.515668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142d4fc706bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bug', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('module', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('github_issue_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('bug', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('github_issue_number')
        batch_op.drop_column('module')
        batch_op.drop_column('severity')

    # ### end Alembic commands ###
